storage_url:
  local: sqlite://#{Dir.pwd}/basic-usersite.sqlite3
  test: sqlite://#{Dir.pwd}/basic-usersite-test.sqlite3
  development: mysql://root:kl33nex@localhost/basic-usersite
  production:  mysql://root:kl33nex@localhost/basic-usersite

remote_syslog:
  development: syslog://logs.papertrailapp.com:52890/basic-usersite-dev
  production:  syslog://logs.papertrailapp.com:52890/basic-usersite-prod
